#!/bin/sh

# Wait for the device to be connected
adb wait-for-device

# Apply the settings
adb shell settings put global force_all_apps_standby true
adb shell settings put global quick_doze_enabled true
adb shell settings put global burn_in_protection 1
adb shell settings put global google_core_control 0
adb shell settings put global restricted_device_performance 1,1
adb shell settings put global sem_low_heat_mode 1
adb shell settings put global sem_wifi_l4s_enabled 1
adb shell settings put global battery_saver_constants advertise_is_enabled=true,enable_night_mode=true,fullbackup_deferred=true,keyvaluebackup_deferred=true,location_mode=0,adjust_brightness_factor=0.5,force_all_apps_standby=true,force_background_check=true,quick_doze_enabled=true
adb shell settings put system power_mode 0
adb shell settings put global safe_wifi 1
adb shell settings put global low_heat_mode 1
adb shell settings put global zram_enable 1
adb shell dumpsys deviceidle enable
adb shell dumpsys deviceidle force-idle
adb shell settings put global background_process_limit 1
adb shell settings put global device_idle_constants inactive_to=600000,sensing_to=120000,locating_to=30000,motion_inactive_to=300000,idle_after_inactive_to=600000,idle_pending_to=120000,max_idle_pending_to=300000,idle_pending_factor=2.0,idle_to=7200000,max_idle_to=43200000,idle_factor=2.0,min_time_to_alarm=7200000,max_temp_app_whitelist_duration=20000,mms_temp_app_whitelist_duration=10000,sms_temp_app_whitelist_duration=10000

echo "Settings applied successfully."
